import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  const adminHash = await bcrypt.hash('Admin1234!', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@automarket.ro' },
    update: {},
    create: {
      name: 'Administrator',
      email: 'admin@automarket.ro',
      passwordHash: adminHash,
      phone: '+40 721 000 001',
      role: 'ADMIN',
    },
  });

  const sellerHash = await bcrypt.hash('Demo1234!', 12);
  const seller = await prisma.user.upsert({
    where: { email: 'demo@automarket.ro' },
    update: {},
    create: {
      name: 'Ion Popescu',
      email: 'demo@automarket.ro',
      passwordHash: sellerHash,
      phone: '+40 722 123 456',
      role: 'USER',
    },
  });

  const listingsData = [
    {
      title: 'BMW Seria 5 550i xDrive M Sport — Impecabil',
      brand: 'BMW',
      model: 'Seria 5',
      year: 2019,
      price: 185000,
      currency: 'RON',
      mileage: 75000,
      fuelType: 'Benzina',
      transmission: 'Automata',
      engineSize: 4.4,
      powerHp: 462,
      bodyType: 'Sedan',
      color: 'Negru',
      location: 'București',
      description:
        'BMW Seria 5 550i în stare excepțională, full options. Motor V8 biturbo 462 CP, pachet M Sport exterior și interior, display gestural, head-up display, scaune sport încălzite și ventilate, sistem audio Harman Kardon. Mașina a beneficiat de service la dealer autorizat BMW la fiecare revizie. Fără accidente, carte service completă. Disponibil pentru test drive.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&q=80',
        'https://images.unsplash.com/photo-1493238792000-8113da705763?w=900&q=80',
        'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=900&q=80',
      ]),
      isFeatured: true,
      isPremium: true,
      status: 'ACTIVE',
      sellerId: admin.id,
    },
    {
      title: 'Audi A6 3.0 TDI quattro S-Line — Full LED',
      brand: 'Audi',
      model: 'A6',
      year: 2020,
      price: 210000,
      currency: 'RON',
      mileage: 58000,
      fuelType: 'Diesel',
      transmission: 'Automata',
      engineSize: 3.0,
      powerHp: 286,
      bodyType: 'Berlina',
      color: 'Gri Metalic',
      location: 'Cluj-Napoca',
      description:
        'Audi A6 3.0 TDI quattro în stare perfectă. Pachet S-Line, faruri full LED Matrix, navigație MMI Plus, ACC adaptiv, Bang & Olufsen sound system 3D, camera 360°. Service Audi autorizat, istoricul complet disponibil. Primul proprietar în România.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=900&q=80',
        'https://images.unsplash.com/photo-1548899338-b5f55b2cfe05?w=900&q=80',
        'https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&q=80',
      ]),
      isFeatured: true,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: seller.id,
    },
    {
      title: 'Mercedes-Benz E 220d AMG Line — 2021',
      brand: 'Mercedes-Benz',
      model: 'Clasa E',
      year: 2021,
      price: 245000,
      currency: 'RON',
      mileage: 42000,
      fuelType: 'Diesel',
      transmission: 'Automata',
      engineSize: 2.0,
      powerHp: 194,
      bodyType: 'Sedan',
      color: 'Alb',
      location: 'Timișoara',
      description:
        'Mercedes-Benz E 220d AMG Line, aproape nou. Pachet AMG exterior, MBUX cu ecran dual 12.3", scaune din piele Nappa cu masaj, suspensie pneumatică AIRMATIC, Burmeister sound system. Garanție activă până în 2024. Unic proprietar, fără daune.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&q=80',
        'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=900&q=80',
        'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=900&q=80',
      ]),
      isFeatured: false,
      isPremium: true,
      status: 'ACTIVE',
      sellerId: admin.id,
    },
    {
      title: 'Porsche Cayenne S V8 — Panoramic, BOSE',
      brand: 'Porsche',
      model: 'Cayenne',
      year: 2018,
      price: 310000,
      currency: 'RON',
      mileage: 88000,
      fuelType: 'Benzina',
      transmission: 'Automata',
      engineSize: 2.9,
      powerHp: 440,
      bodyType: 'SUV',
      color: 'Argintiu',
      location: 'București',
      description:
        'Porsche Cayenne S biturbo, exemplar de colecție. Jante Cayenne Turbo 21", suspensie pneumatică PASM, Sport Chrono Package, BOSE Surround Sound, PCM cu navigație. Service Porsche la zi, inspecție tehnică nouă. Stare ca nouă.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=900&q=80',
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&q=80',
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=900&q=80',
      ]),
      isFeatured: true,
      isPremium: true,
      status: 'ACTIVE',
      sellerId: seller.id,
    },
    {
      title: 'Tesla Model 3 Long Range AWD — Autopilot',
      brand: 'Tesla',
      model: 'Model 3',
      year: 2022,
      price: 278000,
      currency: 'RON',
      mileage: 31000,
      fuelType: 'Electric',
      transmission: 'Automata',
      engineSize: null,
      powerHp: 480,
      bodyType: 'Sedan',
      color: 'Alb Perlat',
      location: 'Cluj-Napoca',
      description:
        'Tesla Model 3 Long Range AWD, autonomie 560 km (WLTP). Autopilot inclus, Premium Audio cu 14 difuzoare, încălzire pentru toate scaunele, jante 19" Gemini. Bateria la 98% capacitate, niciodată reparat. Actualizări software incluse. Taxă de poluare 0.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=900&q=80',
        'https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=900&q=80',
        'https://images.unsplash.com/photo-1549317661-bd32c8ce0729?w=900&q=80',
      ]),
      isFeatured: true,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: admin.id,
    },
    {
      title: 'Volkswagen Passat 2.0 TDI DSG — Highline',
      brand: 'Volkswagen',
      model: 'Passat',
      year: 2019,
      price: 98000,
      currency: 'RON',
      mileage: 112000,
      fuelType: 'Diesel',
      transmission: 'Automata',
      engineSize: 2.0,
      powerHp: 150,
      bodyType: 'Berlina',
      color: 'Albastru Metalic',
      location: 'Brașov',
      description:
        'VW Passat Highline, dotat cu navigație Discover Pro, Active Info Display digital, ACC, Lane Assist, scaune față cu masaj, trapa panoramică. Consum redus 5.5L/100km. Service VW autorizat, carte service completă. Mașină de familie impecabilă.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=900&q=80',
        'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=900&q=80',
        'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=900&q=80',
      ]),
      isFeatured: false,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: seller.id,
    },
    {
      title: 'Range Rover Sport SDV6 HSE — Full Options',
      brand: 'Land Rover',
      model: 'Range Rover Sport',
      year: 2017,
      price: 285000,
      currency: 'RON',
      mileage: 130000,
      fuelType: 'Diesel',
      transmission: 'Automata',
      engineSize: 3.0,
      powerHp: 306,
      bodyType: 'SUV',
      color: 'Negru',
      location: 'București',
      description:
        'Range Rover Sport SDV6 HSE în configurație completă. Suspensie pneumatică, Terrain Response 2, panoramic glass roof, InControl Touch Pro Duo, Meridian Surround Sound, camera 360°. Motorul proaspăt verificat, distribuție nouă. Cunoscut ca cea mai capabilă mașină off-road premium.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=900&q=80',
        'https://images.unsplash.com/photo-1547505734-b56b96916d51?w=900&q=80',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
      ]),
      isFeatured: true,
      isPremium: true,
      status: 'ACTIVE',
      sellerId: admin.id,
    },
    {
      title: 'Volvo XC90 D5 AWD Inscription — 7 Locuri',
      brand: 'Volvo',
      model: 'XC90',
      year: 2018,
      price: 185000,
      currency: 'RON',
      mileage: 95000,
      fuelType: 'Diesel',
      transmission: 'Automata',
      engineSize: 2.0,
      powerHp: 235,
      bodyType: 'SUV',
      color: 'Gri Deschis',
      location: 'Iași',
      description:
        'Volvo XC90 D5 AWD Inscription, 7 locuri, stare excelentă. Sistem audio Bowers & Wilkins 1400W, tapițerie piele Nappa ventilată, Pilot Assist, Air Quality System, scaune al 3-lea rând retractabile electric. Cel mai sigur SUV din clasa sa.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1529180979161-06b8b6d6f2be?w=900&q=80',
        'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=900&q=80',
        'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80',
      ]),
      isFeatured: false,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: seller.id,
    },
    {
      title: 'Skoda Superb 2.0 TDI DSG Sportline — Impecabil',
      brand: 'Skoda',
      model: 'Superb',
      year: 2020,
      price: 115000,
      currency: 'RON',
      mileage: 68000,
      fuelType: 'Diesel',
      transmission: 'Automata',
      engineSize: 2.0,
      powerHp: 190,
      bodyType: 'Berlina',
      color: 'Gri Magnetic',
      location: 'Sibiu',
      description:
        'Skoda Superb Sportline, configurație premium. Faruri full LED Matrix, Virtual Cockpit, Canton sound system, CarPlay + Android Auto, scaune sport din piele, trapa panoramică electrică. Spațiu interior excepțional, portbagaj 625L. Cel mai bun raport calitate-preț din clasă.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=900&q=80',
        'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900&q=80',
        'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=900&q=80',
      ]),
      isFeatured: false,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: admin.id,
    },
    {
      title: 'Toyota RAV4 2.5 Hybrid AWD-i — Dynamic Plus',
      brand: 'Toyota',
      model: 'RAV4',
      year: 2021,
      price: 172000,
      currency: 'RON',
      mileage: 44000,
      fuelType: 'Hibrid',
      transmission: 'Automata',
      engineSize: 2.5,
      powerHp: 222,
      bodyType: 'SUV',
      color: 'Roșu Metalic',
      location: 'Cluj-Napoca',
      description:
        'Toyota RAV4 Hybrid AWD-i Dynamic Plus, consum mediu 5.5L/100km. JBL Premium Audio, Toyota Safety Sense 2.0, wireless charging, camera 360°, tapițerie semipiele. Garanție Toyota până în 2026. Zero probleme mecanice, fiabilitate recunoscută mondial.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
        'https://images.unsplash.com/photo-1544298408-50985a61703c?w=900&q=80',
        'https://images.unsplash.com/photo-1469285994282-454ceb49e63c?w=900&q=80',
      ]),
      isFeatured: false,
      isPremium: true,
      status: 'ACTIVE',
      sellerId: seller.id,
    },
    {
      title: 'Ford Mustang GT 5.0 V8 — 450 CP, Manual 6+1',
      brand: 'Ford',
      model: 'Mustang',
      year: 2019,
      price: 228000,
      currency: 'RON',
      mileage: 52000,
      fuelType: 'Benzina',
      transmission: 'Manuala',
      engineSize: 5.0,
      powerHp: 450,
      bodyType: 'Coupe',
      color: 'Portocaliu Racing',
      location: 'București',
      description:
        'Ford Mustang GT 5.0 V8 în culoarea originală Twister Orange. Motor V8 Coyote 450 CP, cutie manuală 6 trepte, diferențial electronic activ, Brembo brake kit, B&O Play premium audio, Active Exhaust. Taxe plătite, înmatriculată în România. O mașină unică ce atrage toate privirile.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1584345604476-8ec5f452d1d2?w=900&q=80',
        'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=900&q=80',
        'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=900&q=80',
      ]),
      isFeatured: true,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: admin.id,
    },
    {
      title: 'Dacia Duster 1.3 TCe 4x4 Prestige — Nou',
      brand: 'Dacia',
      model: 'Duster',
      year: 2022,
      price: 72000,
      currency: 'RON',
      mileage: 18000,
      fuelType: 'Benzina',
      transmission: 'Manuala',
      engineSize: 1.3,
      powerHp: 150,
      bodyType: 'SUV',
      color: 'Verde Highland',
      location: 'Craiova',
      description:
        'Dacia Duster 1.3 TCe 150 CP 4x4 Prestige, practic nou. MediaNav Evolution 7", cameră marșarier, senzori parcare față-spate, climatizare automată, cruise control adaptiv, jante aliaj 17". Motorul turbo 1.3 TCe Renault Group — fiabil și economic. Primul proprietar.',
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=900&q=80',
        'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=900&q=80',
        'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=900&q=80',
      ]),
      isFeatured: false,
      isPremium: false,
      status: 'ACTIVE',
      sellerId: seller.id,
    },
  ];

  for (const data of listingsData) {
    await prisma.listing.create({ data });
  }

  console.log('Seed completed:');
  console.log('  Admin:  admin@automarket.ro / Admin1234!');
  console.log('  Demo:   demo@automarket.ro  / Demo1234!');
  console.log(`  Listings: ${listingsData.length} created`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
